// LJS

#pragma once

#include "NativeGameplayTags.h"

namespace RPGGameplayTag
{
	RPGPORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_Keyboard);
	RPGPORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	RPGPORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump_Keyboard);
	
	RPGPORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_FighterNone);
}